---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ansible-awx
    image: geerlingguy/docker-ubuntu1804-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  options:
    v: true
  lint:
    name: ansible-lint
  playbooks:
    prepare: prepare.yml
    converge: playbook.yml
    side_effect: side_effect.yml
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
