---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ansible-awx
    image: ubuntu:${UBUNTU_IMAGE_TAG:-latest}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
provisioner:
  name: ansible
  options:
    v: true
  lint:
    name: ansible-lint
  playbooks:
    prepare: prepare.yml
    converge: playbook.yml
    side_effect: side_effect.yml
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
