---
- name: Prepare
  hosts: all
  become: true
  vars:
    git_config: []
    pip_install_packages:
      - name: docker
      - name: ansible
    nodejs_version: 8
    nodejs_install_packages: []
  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      register: result
      until: result is success
      retries: 5
      delay: 5
  roles:
    - calvinbui.ansible_git
    - calvinbui.ansible_pip
    - calvinbui.ansible_nodejs
    - calvinbui.ansible_docker
