---

- name: Side Effect
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Stop AWX containers
      docker_container:
        name: "{{ item }}"
        state: absent
      loop:
        - awx_task
        - awx_web
        - postgres
        - memcached
        - rabbitmq
